"""add openai_oauth_external_disabled to settings

Revision ID: a1b2c3d4e5f6
Revises: 78475bbce762
Create Date: 2026-07-10 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '78475bbce762'
branch_labels = None
depends_on = None


def _column_exists(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists('settings', 'openai_oauth_external_disabled'):
        op.add_column(
            'settings',
            sa.Column('openai_oauth_external_disabled', sa.Boolean(), nullable=False, server_default=sa.false()),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _column_exists('settings', 'openai_oauth_external_disabled'):
        op.drop_column('settings', 'openai_oauth_external_disabled')
    # ### end Alembic commands ###
